global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: consensus-nodes
    metrics_path: /metrics
    static_configs:
      - targets:
          - node-1:9090
          - node-2:9090
          - node-3:9090
          - node-4:9090
          - node-5:9090
